-- Georgia Teacher Planner - Supabase schema
-- Run this once in the Supabase SQL editor for a new project.

create extension if not exists pgcrypto;

create type public.app_role as enum ('admin','teacher');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  role public.app_role not null default 'teacher',
  ai_enabled boolean not null default false,
  ai_monthly_limit integer not null default 50 check (ai_monthly_limit >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(id,display_name)
  values(new.id,coalesce(new.raw_user_meta_data->>'display_name',''));
  return new;
end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create table public.planner_states (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table public.standards (
  id text primary key,
  grade text not null,
  subject text not null,
  course text not null,
  unit text not null default '',
  code text not null,
  description text not null,
  topics jsonb not null default '[]'::jsonb,
  source text not null default 'Georgia Department of Education',
  source_url text,
  version text not null,
  effective_year text,
  is_current boolean not null default true,
  imported_at timestamptz not null default now(),
  unique(version,code,course)
);
create index standards_filter_idx on public.standards(subject,grade,is_current);

create table public.standard_frameworks (
  id text primary key,
  title text not null,
  subject text not null,
  version text,
  last_change_at timestamptz,
  status_start_date date,
  official_source_url text,
  item_count integer not null default 0,
  synced_at timestamptz not null default now()
);

create table public.standard_progressions (
  id text primary key,
  framework_id text references public.standard_frameworks(id) on delete cascade,
  from_standard_id text references public.standards(id) on delete cascade,
  to_standard_id text references public.standards(id) on delete cascade,
  relation text not null default 'precedes',
  sequence_number integer,
  unique(framework_id,from_standard_id,to_standard_id,relation)
);
create index standard_progression_from_idx on public.standard_progressions(from_standard_id);
create index standard_progression_to_idx on public.standard_progressions(to_standard_id);

create table public.site_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

create table public.ai_usage (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  task text not null,
  model_alias text not null,
  provider_model text,
  input_tokens integer not null default 0,
  output_tokens integer not null default 0,
  estimated_cost numeric(12,6) not null default 0,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.planner_states enable row level security;
alter table public.standards enable row level security;
alter table public.site_settings enable row level security;
alter table public.standard_frameworks enable row level security;
alter table public.standard_progressions enable row level security;
alter table public.ai_usage enable row level security;

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin');
$$;

create policy "profiles read own or admin" on public.profiles for select using (id=auth.uid() or public.is_admin());
create policy "profiles admin update" on public.profiles for update using (public.is_admin()) with check (public.is_admin());
create policy "planner state own" on public.planner_states for all using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy "standards public read" on public.standards for select using (true);
create policy "standards admin write" on public.standards for all using (public.is_admin()) with check (public.is_admin());
create policy "site settings admin" on public.site_settings for all using (public.is_admin()) with check (public.is_admin());
create policy "frameworks public read" on public.standard_frameworks for select using (true);
create policy "frameworks admin write" on public.standard_frameworks for all using (public.is_admin()) with check (public.is_admin());
create policy "progressions public read" on public.standard_progressions for select using (true);
create policy "progressions admin write" on public.standard_progressions for all using (public.is_admin()) with check (public.is_admin());
create policy "ai usage read own or admin" on public.ai_usage for select using (user_id=auth.uid() or public.is_admin());
create policy "ai usage edge insert" on public.ai_usage for insert with check (user_id=auth.uid());

-- After creating your own account, promote it once from the SQL editor:
-- update public.profiles set role='admin' where id=(select id from auth.users where email='YOUR_EMAIL');
